name: CI-CD Elastic beanstalk_AWS

env:
 EB_S3_PACKAGE_BUCKET_NAME: "dior-app-pythonpackages"
 EB_APPLICATION_NAME      : "MyFlask"
 EB_ENVIRONMENT_NAME      : "MyFlask-env"
 DEPLOY_PACKAGE_NAME      : "flask_app_${{ github.sha }}.zip"
 AWS-REGION_NAME          : "us-east-1"

on:
  
  push:
    branches: 
      - main 
jobs:
  my_ci_part1:
    runs-on: ubuntu-latest

    steps:
     - name: Git clone repository
       uses: actions/checkout@v2
       
       
     - name: Create zip deployment package
       run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git* 
         
     - name: Configure my AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with: 
        aws-access-key-id: ${{ secrets.My_aws_access_key }}
        aws-secret-access-key : ${{ secrets.my_aws_secret_key }}
        aws-region : ${{ env.AWS-REGION_NAME }}
     
     - name: Copy Deployment package to s3 bucket
       run:  aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_S3_PACKAGE_BUCKET_NAME }}/
      
     - name: Print Happy Message for CI part1
       run: echo "CI Pipeline Finished successfull"
     

  my-cd-part2:  
   runs-on: ubuntu-latest
   needs: [my_ci_part1]  
   
   steps: 
     - name: Configure my AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with: 
        aws-access-key-id: ${{ secrets.My_aws_access_key }}
        aws-secret-access-key : ${{ secrets.my_aws_secret_key }}
        aws-region : ${{ env.AWS-REGION_NAME }}
     
     - name: Create new Elastic Beanstalk APP version
       run: |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.EB_APPLICATION_NAME }} \
        --source-bundle S3Bucket="${{ env.EB_S3_PACKAGE_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
        --version-label "ver-${{ github.sha }}" \
        --description "commitSHA-${{ github.sha }}" 
   
     - name: Deploy new Elastic Beanstalk APP version
       run: aws elasticbeanstalk update-environment
             --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "ver-${{ github.sha }}"
              
     - name: Print Happy Message for CI part1
       run: echo "CD Pipeline Finished successfull" 
